### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

### ISSUE THREAD

**Issue by coderhh** [Iftakharpy/algoexpert-download#3]
when download videos, got this error

**Comment by Iftakharpy** [comment]
@coderhh, can you provide more information about how to produce the error and more info about the error?

**Comment by Iftakharpy** [comment]
If you have solved your issue please share the info about how you solved the issue.
If you are still having the issue please provide more info to help solve the issue.

**Comment by Iftakharpy** [comment]
@coderhh I will be waiting until next week for your reply. If you don't reply within this week I will close this issue.
