### ISSUE TITLE
Can't run main type|type error

### ISSUE THREAD

**Issue by UomoLepre** [Iftakharpy/algoexpert-download#4]
File "C:\...\algoexpert-download-main\practice_environment_builder\starter_test_file_writter.py", line 15, in <module>
    def get_tester_code(question_object:dict|list, question_tests_object:dict|list, module_to_test:str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by Iftakharpy** [comment]
Which version of python are you using? I think you should use the latest version of python.
